<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cook</string>
	</array>
	<key>name</key>
	<string>Cook</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>([A-Za-z]+)(\ *)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.ssraw</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.ssraw</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>classes</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.character</string>
				</dict>
			</dict>
			<key>name</key>
			<string>variable.complex.ssraw</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)</string>
					<key>end</key>
					<string>(&gt;)</string>
					<key>name</key>
					<string>string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>comment</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([A-Za-z0-9\-]+)(\:)(\ *)([A-Za-z0-9\-]+)</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>([A-Za-z0-9\-]+)(\:)</string>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.character</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\d+)(\.*)(\d+*)(\ *)((c|tsp|tbsp|oz|F)*)</string>
					<key>name</key>
					<string>meta</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(")</string>
					<key>end</key>
					<string>(")</string>
					<key>name</key>
					<string>string.regexp.set</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>end</key>
					<string>(\))</string>
					<key>name</key>
					<string>string</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(bake|heat|mix|stir|place|cool|serve|whisk)(\ *)([A-Za-z0-9\-]+*)</string>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(on|or|until|and)(\ *)([A-Za-z0-9\-]+*)</string>
					<key>name</key>
					<string>constant.character</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(red)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(purple)</string>
			<key>name</key>
			<string>constant.character</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(blue)</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(gray)</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(white)</string>
			<key>name</key>
			<string>meta</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(yellow)</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(invalid)</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character.character-class.regexp</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.backslash.regexp</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.character-class.regexp</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.other.character-class.set.regexp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(a)(b)(c)(d)(e)(f)(g)(h)(i)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>cook.syntax_name</string>
	<key>uuid</key>
	<string>3bf3df53-40e9-411d-a0b5-869bdccc9f4a</string>
</dict>
</plist>
